language: node_js
node_js:
- "4"  # nodejs的版本
branches:
  only:
  - master  # 设置自动化部署的源码分支

env:
  global:
    secure: Kl6AZLqFTGwm3CAktb3Idl2qNstdkC/SdYpyXJcehNnbubfur5Rqpjsy2UplG37+mzZW33UJszBwOrlu/YgNgMKfGPGGs55WvrayaJrjvnXLetdVW4X7WraviCcWFAcHLTtkhF9gmz9DXWYr8FM+rp16AFKU2uWEx1S8/LhxGsRuMwO1SHJqZbWaMUf20b5hhPnV88nvg19uNOFz2mfzXzsukmv3ccXRUUR+rSPa/ybauZj9qBaDb+y+1bsOGECC3TdiyikInRnX3IZDxf+YxSZGqMSl4wXzHWamVZB03LU3AhfUhfZEOhfFpcJG+nnLuS8h092BiEtpGixTewdtpdRPoil3CASGEQ8JvuZ90T/NaiD6m0HTxLZ4zXrWlPLbtCnPXwWli672XcNEiNgZB8COB0IkWv2FQoPl1H7B6UqdwxSxte3aN5YqVfkY7CiJtu+GAFH8u2JSO0OiK+V773vqz+xdt0fB1tXItL2AQtoSrhrr5QchJN5oZhFQpzr/g97O8gBgAQ2p0GLxY3BiFIccGX4hN1Lls/+0WKHPQ3dfFs49jvmelg6fhrYcYQhH/iVJtkIf3TjPq0CvQhiqzMjZoafle9U8RmuY/q/UaoswmkGHQ97qER5QpBWRpDH6JLQOJ63+aiWM53STyrJdraU+vJGGtc5KfTnkRd1Y82c=

before_install:
- export TZ='Asia/Shanghai'  
- npm install -g hexo
- npm install -g hexo-cli 
before_script:
# ------------------------------------------------
# 设置github账户信息 注意修改成自己的信息
# ------------------------------------------------
- git config --global user.name "xuezhisd"
- git config --global user.email xuezhi@126.com 
# ------------------------------------------------
# github仓库操作  注意将仓库修改成自己的
# ------------------------------------------------
- sed -i'' "s~https://github.com/damotiansheng/damotiansheng.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/damotiansheng/damotiansheng.github.io.git~" _config.yml
# 安装依赖组件
install:
- npm install
# 执行的命令
script:
- hexo clean
- hexo generate
# 执行的成功后执行 
after_success:
- hexo deploy

