language: node_js
node_js:
- "6"  # nodejs的版本
branches:
  only:
  - master  # 设置自动化部署的源码分支

env:
  global:
    secure: gv4se5W3skRqyd4FQ8N5TsTIUgRlULcVLuQJ+mJw3JW89412kjoW3QB9p0nC4qlBLPNvTOYzP24SMv1JX8BTZ6nWIlbubwCgWCNrp8fnmgJHGKvKPuLOGXrbIDrqw478Uuy1Fd63tpgKmk3vpz0igA2JrUvf6dgNzvIiYbcERk6blgYGhPUCl5UCVVrpu4imakor5JPPObNWLZNmzPHr+pA9JSDEOVt9qY5f9fwIF0qP6yEfRpo9OR7w7VwyCR00yu4xjqZCCAWKCczFnd+xOAQpt3o/xAKFPk4+C/HSqbsLmv4+TttHRCK108mxrK1s8w4qPAXIRoHyRUWl0zugW91TOECZ//onacTZ5w52/DgnND/JjMLb/eap23lsVy5ZaPLJ5B2SCd7MWRciggmnkm2X2KXcLtEDXZs0WNSAB3cLv6i0TJ99UVa6KPP35HJn8HVyS2wu1gyp4rFtQ3NtdEPrMpFdL9D6SE+xm5sirdfaLp9K87F1TRhXb9TzsHJUfviF9goo/NoaEbEVkzkxQyuQz55Via/ozLd+daAnBxEdbysb0vllP5oRHmUZwBAO8VTfMYNOVr05a2yhDAG39+MW7ioZ/42GQuvd+OAhADx06AmwBqKOqLYF1PIoVp7aC0gsqHhRhV5jUh61GbJy9ZFi0La5Bbo3N7sSY00d7u0=


before_install:
- export TZ='Asia/Shanghai'  
- npm install -g hexo
- npm install -g hexo-cli 
before_script:
# ------------------------------------------------
# 设置github账户信息 注意修改成自己的信息
# ------------------------------------------------
- git config --global user.name "damotiansheng"
- git config --global user.email 974361900@qq.com
# ------------------------------------------------
# github仓库操作  注意将仓库修改成自己的
# ------------------------------------------------
- sed -i'' "s~https://github.com/damotiansheng/damotiansheng.github.io.git~https://${REPO_TOKEN}:x-oauth-basic@github.com/damotiansheng/damotiansheng.github.io.git~" _config.yml
# 安装依赖组件
install:
- npm install
# 执行的命令
script:
- hexo clean
- hexo generate
# 执行的成功后执行 
after_success:
- hexo deploy

