# Header

menu:
  首页: /
  归档: /archives 
#  随笔: /tags/随笔
#  分类: /categories
  分类: /tags
  相册: /photos
  
# SubNav
subnav:
  github: "https://github.com/damotiansheng"
 #weibo: "http://weibo.com/u/1877550080"
  weibo: "#"
  #rss: "#"
  zhihu: "#"
  douban: "https://www.douban.com/people/wwwzqbxcom/"
  mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

categories: /categories
# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: 阅读全文
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /photos/damotiansheng.png

#是否开启分享
share_jia: false
share_addthis: false
#share_addthis: true

#是否开启网页统计
baidu_tongji: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
#duoshuo: false
duoshuo: dmts

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  tagcloud: '标签'
  friends: '友链'
  aboutme: '关于我'

tagcloud: true

friends:
  csdn博客: http://blog.csdn.net/damotiansheng
  潘柏信博客: http://baixin.io/
  Litten博客: http://litten.github.io

aboutme: 2016年10月13日<br><br>一名计算机蜗牛，努力前进，自强不息<br>
